desc "this task imports all ionic and font awesome icons into database"
task :models_import => [:environment] do 
  models = ["CLA 250",
    "GLA 250",
    "Sprinter 2500 Cargo Van",
    "C 300",
    "GLC 300",
    "Sprinter Extended Cargo Van",
    "GLE 350",
    "E 300",
    "GLC 43",
    "E 450",
    "E 400",
    "GLS 450",
    "E 43",
    "S-Class",
    "Metris Cargo Van",
    "Metris Passenger Van",
    "Sprinter Cargo Van",
    "Sprinter 4500 Cargo Van",
    "GLC 350",
    "Sprinter 2500 Passenger Van",
    "Sprinter 2500 Crew Van",
    "C 43",
    "E 53",
    "E 63",
    "SL 450",
    "GLS 63",
    "GLC 63",
    "S 560",
    "CLS 450",
    "GLS 550",
    "S 450",
    "CLS 63S",
    "G 63",
    "GT C Roadster",
    "C 250",
    'S 550',
    'CLS 550',
    'G 65',      
    'H2',
    'Tundra', 
    'Tacoma',
    'Camaro',      
    'Accord',
    '1500',
    'Enclave',              
    'Denali',              
    'Trailhawk',              
    'Impreza',              
    'Avalon',              
    'Traverse',              
    'Escape',              
    'CR-V',              
    'Prius',              
    'XC70',              
    'Charger',                         
    'ES 350',              
    '2500',              
    'Crosstrek',              
    'Outback',              
    'Corolla',              
    'RAV4',              
    'Explorer',              
    'Terrain',              
    'Sonata',              
    'Wrangler',              
    'Frontier',              
    'Model S',              
    'Camry',              
    'S90',              
    'Journey',              
    'civic',              
    'Optima',              
    'Altima',              
    'Forester',              
    'Legacy',              
    'Veloster',              
    'S60',              
    "E 350"]

    models.each do |model|
      m = Model.new
      m.name = model 
      m.save 
      print "#{model} model added to DB \n \n"
    end

end